name: "Heimdall Dashboard"
version: "1.1.1"
slug: heimdall
description: "ðŸš€ Your Personal Application Dashboard - Organize and access all your web apps, services, and bookmarks from one beautiful, customizable homepage"
maintainer: Christian Orrala <https://github.com/ChristianOrrala>
url: https://github.com/ChristianOrrala/home-assistant-addons
arch:
  - aarch64
  - amd64
  - armv7
  - i386
init: false
homeassistant_api: false
host_network: false
hassio_api: false
panel_icon: mdi:view-dashboard
panel_title: Heimdall
startup: application
ingress: true
ingress_port: 80
webui: http://[HOST]:[PORT:80]

ports:
  80/tcp: 8080
  443/tcp: 8443
ports_description:
  80/tcp: "HTTP Web UI"
  443/tcp: "HTTPS Web UI"

map:
  - addon_config:rw
  - share:ro

options:
  PUID: 1000
  PGID: 1000
  TZ: "America/Chicago"
  ALLOW_INTERNAL_REQUESTS: true
  APP_NAME: "Heimdall"
  http_port: 8080
  https_port: 8443
  restore_backup: ""

schema:
  PUID: int
  PGID: int
  TZ: str
  ALLOW_INTERNAL_REQUESTS: bool
  APP_NAME: str
  http_port: port
  https_port: port
  restore_backup: "str?"
